version: 2

project_name: overhuman

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/overhuman
    binary: overhuman
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  github:
    owner: overhuman
    name: overhuman
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
